name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prerequisites
      run: |
        # sudo apt-get update
        sudo apt-get install -yq asciidoc-base w3m libchromaprint-dev doxygen graphviz
        sudo apt-get install -yq libcue-dev libfuse-dev libsqlite3-dev libavcodec-dev libavformat-dev libswresample-dev libavutil-dev libswscale-dev libavfilter-dev libchardet-dev
        sudo apt-get install -yq libdvdread-dev libdvdnav-dev libbluray-dev
        gcc -v
        ffmpeg -version
    - name: autogen.sh
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: Archive Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Collected test results 
        path: |
           test/*.log
           test/*.trs
           test/*.tag
