name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prerequisites
      run: |
        # sudo apt-get update
        # sudo apt-get install -yq apt-utils
        # sudo apt-get install -yq fuse libfuse2 libsqlite3-0 libavcodec58 libavformat58 libswresample3 libavutil56 libswscale5 libavfilter7 libcue2 libchardet1
        # sudo apt-get install -yq libdvdread[48] libdvdnav4 libbluray2
        # sudo apt-get install -yq gcc g++ make pkg-config 
        sudo apt-get install -yq autoconf asciidoc-base w3m libchromaprint-dev bc doxygen graphviz curl git xxd
        sudo apt-get install -yq libcue-dev libfuse-dev libsqlite3-dev libavcodec-dev libavformat-dev libswresample-dev libavutil-dev libswscale-dev libavfilter-dev libchardet-dev
        sudo apt-get install -yq libdvdread-dev libdvdnav-dev libbluray-dev
    - name: autogen.sh
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
